---
title: "Mapping Incidence of Post-Transfusion Malaria in an Endemic Population"
author: "Clara Harb"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

## Package Loading {-}

```{r load_packages, message = FALSE}
library(here)
library(janitor)
library(skimr)
library(knitr)
library(tidyr)
library(treemap)
library(devtools)
library(d3Tree)
library(d3treeR)
library(treemapify)
library(readr) 
library(lubridate) 
library(ggthemes)
library(htmlwidgets)
library(waterfalls)
library(tidyverse)
```

## Import csv data

```{r, message = FALSE}
mappingmalaria <- read_csv(here("data", "PracticumData.csv"))

mappingmalaria
```

## Cleaning the Data

```{r, message = FALSE}
mappingmalaria1 <- mappingmalaria %>%
  pivot_longer(cols = c(`INF Pf`),
               names_to = "SpeciesPf", values_to = "InfectionPf") %>%
   pivot_longer(cols = c(`INF Pv`),
               names_to = "SpeciesPv", values_to = "InfectionPv")%>%
   pivot_longer(cols = c(`INF Pm`),
               names_to = "SpeciesPm", values_to = "InfectionPm")%>%
   pivot_longer(cols = c(`INF Po`),
               names_to = "SpeciesPo", values_to = "InfectionPo")%>%
   pivot_longer(cols = c(`PCR Pf`),
               names_to = "SpeciesPCRPf", values_to = "InfectionPCRPf")%>%
   pivot_longer(cols = c(`PCR Pv`),
               names_to = "SpeciesPCRPv", values_to = "InfectionPCRPv")%>%
   pivot_longer(cols = c(`PCR Pm`),
               names_to = "SpeciesPCRPm", values_to = "InfectionPCRPm")%>%
   pivot_longer(cols = c(`PCR Po`),
               names_to = "SpeciesPCRPo", values_to = "InfectionPCRPo")

mappingmalaria1
```


```{r, message = FALSE}
mappingmalaria1 <- mappingmalaria1 %>%
  mutate(Infection = case_when(InfectionPf == "1" ~ 'Positive', 
                               InfectionPv == "1" ~ 'Positive',
                               InfectionPm == "1" ~ 'Positive',
                               InfectionPo == "1" ~ 'Positive', 
                               TRUE ~ 'Negative'))
```

```{r, message = FALSE}
mappingmalaria1 <- mappingmalaria1 %>%
  mutate(Species = case_when(InfectionPf == "1" ~ 'P.falciparum', 
                               InfectionPv == "1" ~ 'P.vivax',
                               InfectionPm == "1" ~ 'P.malariae',
                               InfectionPo == "1" ~ 'P.ovale', 
                               TRUE ~ 'No Infection'))
```


```{r, message = FALSE}
mappingmalariapre <- mappingmalaria1 %>%
  select(`Plate ID`, `Lab Use ID`, Species, Infection)
```

```{r, message = FALSE}
mappingmalariapre <- mappingmalariapre %>%
  slice(1:831, 1537:1664)

mappingmalariapre$`Lab Use ID` <- as.numeric(mappingmalariapre$`Lab Use ID`)
mappingmalariapre
```


```{r, message = FALSE}
mappingmalariapost <- mappingmalaria1 %>%
  select(`Plate ID`, `Lab Use ID`, Species, Infection)%>%
  slice(832:1536)
mappingmalariapost
```


## Treemap Pre-Treatment

```{r, message=FALSE}
treemap(mappingmalariapre,
        index=c("Species"),
        vSize="Lab Use ID",
        type="index",
        title="Prevalence of Malaria Infection Pre-Treatment--Disaggregated by Species",
        palette = "Set3")
```


```{r, message= FALSE}
tree <- treemap (mappingmalariapre, index=c("Species", "Plate ID") ,vSize="Lab Use ID" ,vColor="Lab Use ID", type="index", border.col=c("black","white"), palette = "Set3", title="Prevalence of Malaria Infection Pre-Treatment--Disaggregated by Species",
fontsize.title=14, fontsize.labels = 7, title.legend = "Counts" )

int <- d3tree2 (tree,width = "100%", height ="600px", rootname = "Species")

saveWidget(int, file="MalariaPre.html", selfcontained = T)
```


## Treemap Post-Treatment

```{r, message=FALSE}
treemap(mappingmalariapost,
        index=c("Species"),
        vSize="Lab Use ID",
        type="index",
        title="Prevalence of Malaria Infection Post-Treatment--Disaggregated by Species",
        palette = "Set3")
```


```{r, message= FALSE}
tree <- treemap (mappingmalariapost, index=c("Species", "Plate ID") ,vSize="Lab Use ID" ,vColor="Lab Use ID", type="index", border.col=c("black","white"), palette = "Set3", title="Prevalence of Malaria Infection Post-Treatment--Disaggregated by Species",
fontsize.title=14, fontsize.labels = 7, title.legend = "Counts" )

int <- d3tree2 (tree,width = "100%", height ="600px", rootname = "Species")

saveWidget(int, file="MalariaPost.html", selfcontained = T)
```


